name: Deploy Lambda Function Through S3

on:
  push:
    branches:
      - dev
    paths:
      - "lambda_test/hello_world_.py"

env:
  AWS_REGION: "us-east-1"
  S3_BUCKET_NAME: "test-bucket"

jobs:
  Deploy-Lambda-Functions:
    name: Deploy Function
    runs-on: ubuntu-latest

    environment: "dev"
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION}}

      - name: Zip file
        run: zip -jr lambda_test/lambda_function.zip lambda_test/hello_world_.py
      - name: Copy File to S3
        run: |
          aws s3 cp lambda_test/lambda_function.zip s3://test-bucket/localstack_test/
      - name: Upload Function to Lambda
        run: |
          aws lambda update-function-code --function-name "arn:aws:lambda:us-east-1:<account_id>:function:HelloWorldLambda"  --s3-bucket "test-bucket" --s3-key "localstack_test/lambda_function.zip"
      - name: Remove Zip File
        run: rm lambda_test/lambda_function.zip
      - name: Wait for update to finish
        run: aws lambda wait function-updated --function-name "arn:aws:lambda:us-east-1:<account_id>:function:HelloWorldLambda"